routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Redirige la ruta raiz a la vista login
Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

//Route::resource('terapeuta', 'TerapeutaController');
Route::resource('user', 'UserController');
Route::resource('citas','AppointmentController');
Route::resource('paciente', 'PatientController');
//Route::resource('paciente', 'PacienteController');
//Route::resource('cita', 'CitaController');

//Route::post('citaNueva','CitaController@citaNueva');

app/User.php
<?php

namespace App;

use App\Note;
use App\Notifications\ResetPasswordNotification;
use App\Patient;
use App\Presenters\UserPresenter;
use App\Role;
use App\Speciality;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'dni','name', 'surname', 'second_surname', 'birthdate', 'address', 'phone','email', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    //Este metodo encripta la variable password automaticamente. Desde cualquier sitio que se guarde la variable password de un usuario va a interactuar este metodo automatico
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    public function note()
    {        
        // En esta ocasion establecemos morphOne pk es una relacion polimorfica. Recibe como parametro la llave o prefijo que usamos al crear la migracion
        return $this->morphOne(Note::class, 'notable');
    }

    public function patient()
    {
        return $this->belongsToMany(Patient::class);
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function specialities()
    {
        return $this->belongsToMany(Speciality::class);
    }

    public function present()
    {
        return new UserPresenter($this);
    }

    

    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserFormRequest;
use App\Interfaces\UserInterface;
use App\Role;
use App\Speciality;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    protected $users;

    public function __construct(UserInterface $user){
        $this->users = $user;
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->users->index();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');
        $specialities = Speciality::pluck('display_name', 'id');
        return view('users.create', compact('roles', 'specialities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserFormRequest $request)
    {
        $user = $this->users->store($request);
        return redirect()->route('user.index')->with('info', 'Usuario creado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->users->show($id);
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::pluck('display_name', 'id');
        $specialities = Speciality::pluck('display_name', 'id');
        $user = $this->users->show($id);
        return view('users.edit', compact('user', 'roles', 'specialities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserFormRequest $request, $id)
    {
        //dd($id);
        $user = $this->users->update($request, $id);
        return back()->with('info', 'Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //dd($id);
        $user = $this->users->destroy($id);
        return redirect()->route('user.index');
    }
}

resources/views/users/create.blade.php
<!-- Esta seccion servira para crear un nuevo paciente -->
@extends('layouts.app')
@section('contenido')
<div class="content-wrapper py-4">
	<section class="content">
	    <!-- Main content -->
	     
	    	<div class="col-12"> 
			    <div class="card">
			        <div class="card-header">
			            <h3 class="card-title">Nuevo usuario</h3>
			        </div>
			        <div class="card-body">
				        <!-- Si no tenemos errores no mostramos el div -->
				        @if (count($errors)>0)
				        <div class="alert alert-danger">
				            <ul>
				                @foreach($errors -> all() as $error)
				                <!-- error lo vamos a recibir de nuestro archivo request -->
				                <li>{{$error}}</li>
				                @endforeach
				            </ul>
				        </div>
				        @endif
						<form  method="POST" action="{{ route('user.store') }}">
						@csrf
						@include('users.form', ['btnText' => 'Guardar', 'user' => new App\User])	
						</form>
					</div>
				</div>
			</div>		
	</section>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('contenido')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper py-3">
	  <!-- Main content -->
	@if(session()->has('info'))
		<div class="alert alert-success">{{session('info')}}</div>
	@endif
    <section class="content">      	
    	<div class="card">
            <div class="card-header">
            	<h3 class="card-title">Editar usuario: {{$user -> name.' ' .$user -> surname.' ' .$user -> second_surname}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">	
            	<form  method="POST" action="{{ route('user.update', $user-> id) }}">
				@method('PATCH')
				
				@include('users.form', ['btnText' => 'Editar'])
				</form>
			</div>
			<!-- /.card-body -->
		</div>
		<!-- /.card -->
	</section>
</div>
@endsection

resources/views/users/form.blade.php
@csrf 		
<img class="py-2" width="100px" src="{{asset('img/fotoCV.jpg')}}">

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "dni"> DNI</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="dni" required value="{{old('dni', $user->dni)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "name"> Nombre</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="name" required value="{{old('name', $user->name)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "surname">Apellido</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="surname" required value="{{old('surname', $user->surname)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "codigo">Segundo apellido</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="second_surname"  value="{{old('second_surname', $user -> second_surname)}}" class="form-control">
		</div>
	</div>	
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "birthdate">Fecha de nacimiento</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="birthdate" required value="{{old('birthdate', $user->birthdate)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "address">Direccion</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="address" required value="{{old('address', $user->address)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "phone">Telefono</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="phone" required value="{{old('phone', $user->phone)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "email">Email</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="email" required value="{{old('email', $user->email)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "specialities">Especialidad</label>
			<div class="checkbox">
			@foreach($specialities as $id => $name)
			<label>
				<!-- para que se marquen los roles que hay usamos el siguiente pluck-->
				<input
					type="checkbox"
					required
					value="{{$id}}"
					{{$user->specialities->pluck('id')->contains($id) ? 'checked' : ''}}
					name="specialities[]"->{{$name}}
			</label>
			@endforeach
			<br>
		</div>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<label for="role">Roles</label>
		<div class="checkbox">
			@foreach($roles as $id => $name)
			<label>
				<!-- para que se marquen los roles que hay usamos el siguiente pluck-->
				<input
					type="checkbox"
					required
					value="{{$id}}"
					{{$user->roles->pluck('id')->contains($id) ? 'checked' : ''}}
					name="role[]"->{{$name}}
			</label>
			@endforeach
			<br>
		</div>
	</div>
	<!-- Para ocultar estos campos a la hora de actualizar, preguntamos si el usuario tiene un id. Si tiene un id significa que estamos editando y no lo muestra -->
	@unless ($user->id)
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for="password">Contraseña</label>
			<input class="form-control" type="password" name="password" required>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for="password_confirmation">Confirma contraseña</label>
			<input class="form-control" type="password" name="password_confirmation" required>
		</div>
	</div>
	@endunless	
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="{{$btnText}}">
		</div>
	</div>
</div>
<!-- /.row -->

resources/views/users/index.blade.php
@extends('layouts.app')
@section('contenido')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper py-4">
    <!-- Main content -->
    <section class="content">
      	<div class="row">
        	<div class="col-12">
		        <div class="card">
		            <div class="card-header">
		            	<h3 class="card-title py-3">Usuarios</h3>
		              	<div class="row float-right py-3 px-3">
							<a href="{{route('user.create')}}"><i class="fas fa-plus" style="font-size: 20px"></i></a>						
						</div>
		            </div>
		            <!-- /.card-header -->
		            <div class="card-body">
		     			<table id="user" class="table table-bordered table-striped">
					        <thead>
				                <tr>
									<th>Nombre</th>
									<th>Apellidos</th>
									<th>Telefono</th>
									<th>Email</th>
									<th>Role</th>
									<th>Opciones</th>
								</tr>
							</thead>
							<tbody>								
								@foreach ($users as $user)
								<tr>
									<td>{!!$user->present()->link()!!}</td>
									<td>{{$user -> surname.' ' .$user -> second_surname}}</td>
									<td>{{$user -> phone}}</td>	
									<td>{{$user -> email}}</td>
									<td>{{$user->present()->roles()}}</td>	
									<td>										 
										<a href="{{route('user.edit', $user->id)}}"><i class="far fa-edit px-2"></i></a>
										<a href="" data-target="#modal_delete{{$user->id}}" data-toggle="modal"><i class="far fa-trash-alt px-2"></i></a>
									</td>
								</tr>
								@include('users.modal')
								@endforeach
							</tbody>					
						</table>
					</div>		
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/users/modal.blade.php
<div class="modal fade" id="modal_delete{{$user->id}}">
	<div class="modal-dialog">
  		<div class="modal-content">
        <form id="deleteuser" style="display:inline" method="POST" action="{{route('user.destroy',$user->id)}}">
        @method('DELETE')
        @csrf

          <div class="modal-header">
            	<h4 class="modal-title">Eliminar usuario {{$user->name}}</h4>
            	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
              	<span aria-hidden="true">&times;</span>
            	</button>
          </div>
          <div class="modal-body">
            	<p>Confirme si desea eliminar el usuario {{$user->id}}</p>
          </div>
          <div class="modal-footer justify-content-between">
            	<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            	<button class="btn btn-danger" type="submit" class="btn btn-primary" >Eliminar</button>
          </div>                     
        </form>
      </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

resources/views/users/show.blade.php
@extends('layouts.app')
@section('contenido')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper py-3">
	  <!-- Main content -->
    <section class="content">      	
    	<div class="card">
            <div class="card-header">
            	<h3 class="card-title">{{$user -> name.' ' .$user -> surname.' ' .$user -> second_surname}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">			
				<img class="py-2" width="100px" src="../img/fotoCV.jpg">
				<div class="row float-right py-3 px-3">
					<a href="{{route('user.edit', $user->id)}}"><i class="far fa-edit px-4" style="font-size: 25px"></i></a>
					<a href="" data-target="#modal_delete{{$user->id}}" data-toggle="modal"><i class="far fa-trash-alt px-3" style="font-size: 25px"></i></a>
					@include('users.modal')
				</div>					
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "nombre"> DNI</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="dni" value="{{$user -> dni}}" class="form-control"disabled style= "background-color:#FFFFFF ">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "name"> Nombre</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="name" value="{{$user -> name}}" class="form-control"disabled style="background-color:#FFFFFF" >
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "surname">Apellido</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="surname" value="{{$user -> surname}}" class="form-control"disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "second_surname">Segundo apellido</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="second_surname"  value="{{$user -> second_surname}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label>Role</label>
								<input type="text" name="role"  value="{{$user->present()->roles()}}" class="form-control" disabled style="background-color:#FFFFFF">	
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "birthdate">Fecha de nacimiento</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="birthdate" value="{{$user -> birthdate}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "address">Direccion</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="address" value="{{$user -> address}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "phone">Telefono</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="phone" value="{{$user -> phone}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "email">Email</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="email" required value="{{$user -> email}}" class="form-control"disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "specialities">Especialidad</label>
							<input type="text" name="specialities" value="{{$user -> present()->specialities()}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>												
				</div>
				<!-- /.row -->
			</div>
			<!-- /.card-body -->
		</div>
		<!-- /.card -->
	</section>
</div>
@endsection