routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Redirige la ruta raiz a la vista login
Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

//Route::resource('terapeuta', 'TerapeutaController');
Route::resource('user', 'UserController');
Route::resource('citas','AppointmentController');
Route::resource('paciente', 'PatientController');
//Route::resource('paciente', 'PacienteController');
//Route::resource('cita', 'CitaController');

//Route::post('citaNueva','CitaController@citaNueva');

app/Patient.php
<?php

namespace App;

use App\Appointment;
use App\Presenters\PatientPresenter;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    

     protected $fillable = [        
    	'dni', 'name', 'surname', 'second_surname', 'birthdate', 'address',	'phone', 'email', 'reason_visit'
    ];

    public function note()
    {
        // En esta ocasion establecemos morphOne pk es una relacion polimorfica. Recibe como parametro la llave o prefijo que usamos al crear la migracion
        return $this->morphOne(Note::class, 'notable');
    }
     
   // public function user()
   // {
   // 	return $this->belongsTo(User::class);
   // }

    public function user()
    {
        return $this->belongsToMany(User::class);
    }

	public function appointment()
    {
        return $this->hasMany(Appointment::class);
    }

    public function present()
    {
        return new PatientPresenter($this);
    }


}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PatientFormRequest;
use App\Interfaces\PatientInterface;
use Illuminate\Http\Request;

class PatientController extends Controller
{
    protected $patients;

     public function __construct(PatientInterface $patient){
        $this->patients = $patient;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {    	
        $patients = $this->patients->index();
        return view('patients.index', compact('patients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PatientFormRequest $request)
    {
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $patient = $this->patients->show($id);  
        return view('patients.show', compact('patient')); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PatientFormRequest $request, $id)
    {
        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        

    }


}

resources/views/patients/create.blade.php
<!-- Esta seccion servira para crear un nuevo paciente -->
@extends('layouts.app')
@section('contenido')
<div class="content-wrapper py-4">
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Nuevo paciente</h3>
                        </div>
                        <!-- Si no tenemos errores no mostramos el div -->
                        @if (count($errors)>0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors -> all() as $error)
                                <!-- error lo vamos a recibir de nuestro archivo request -->
                                <li>{{$error}}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        <!-- Creamos un formulario para poder registrar los nuevos pacientes.
						Enviamos los parametros de nuestro formulario mediante un Array. Le enviamos la ruta especifica con la que estamos trabajando. Esta ruta se ha especificado en el archivo web.php de la carpeta routes, donde le decimos que esa ruta se va a encargar de trabajar con ArticuloController que es el que se encarga de la logica. El metodo al ser POST va a llamar a la funcion store, si es patch a update, si es delete a destroy  -->
                        <form method="POST" action="{{ route('paciente.store') }}">
                        @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre"> Nombre</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="nombre" required value="{{old('nombre')}}" class="form-control" placeholder="Nombre...">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Terapeuta</label>
                                            <select name="terapeuta_id" class="form-control">
                                                @foreach($terapeutas as $tera)
                                                <option value="{{$tera->id_terapeuta}}">{{$tera->nombre}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="codigo">Apellido 1</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="apellido1" required value="{{old('apellido1')}}" class="form-control" placeholder="Apellido...">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre">Apellido 2</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="apellido2" value="{{old('apellido2')}}" class="form-control" placeholder="Apellido...">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre">DNI</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="dni" required value="{{old('dni')}}" class="form-control" placeholder="DNI...">
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre">Fecha de nacimiento</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input class="form-control datepicker" type="text" name="fecha_nacimiento" required value="{{old('fecha_nacimiento')}}" class="form-control" placeholder="Fecha de nacimiento...">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre">Direccion</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="direccion" required value="{{old('direccion')}}" class="form-control" placeholder="Direccion...">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre">Telefono</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="telefono" required value="{{old('telefono')}}" class="form-control" placeholder="Telefono...">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="nombre">Email</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="email" required value="{{old('eamil')}}" class="form-control" placeholder="Email...">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 ">
                                        <div class="form-group">
                                            <label for="nombre">Historial</label>
                                            <!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
                                            <input type="text" name="historial" required value="{{old('historial')}}" class="form-control" placeholder="Historial...">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">

                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label for="motivo_consulta">Motivo de la consulta</label>
                                            <input type="text" name="motivo_consulta" required value="{{old('motivo_consulta')}}" class="form-control" placeholder="Motivo de la consulta...">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 py-2">
                                        <div class="form-group float-right  ">
                                            <br>
                                            <button class="btn btn-primary px-4" type="submit">Guardar</button>
                                            <button class="btn btn-danger px-4" type="reset">Cancelar</button>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.col-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>	
</div>
<!-- /.wrapper -->
	
@endsection

resources/views/patients/edit.blade.php
@extends('layouts.app')
@section('contenido')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper py-3">
	  <!-- Main content -->
	@if(session()->has('info'))
		<div class="alert alert-success">{{session('info')}}</div>
	@endif
    <section class="content">      	
    	<div class="card">
            <div class="card-header">
            	<h3 class="card-title">Editar pacient: {{$patient -> name.' ' .$patient -> surname.' ' .$patient -> second_surname}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">	
            	<form  method="POST" action="{{ route('paciente.update', $patient-> id) }}">
				@method('PATCH')
				
				@include('patients.form', ['btnText' => 'Editar'])
				</form>
			</div>
			<!-- /.card-body -->
		</div>
		<!-- /.card -->
	</section>
</div>
@endsection

resources/views/patients/form.blade.php
@csrf 		
<img class="py-2" width="100px" src="{{asset('img/fotoCV.jpg')}}">

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "dni"> DNI</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="dni" required value="{{old('dni', $user->dni)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "name"> Nombre</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="name" required value="{{old('name', $user->name)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "surname">Apellido</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="surname" required value="{{old('surname', $user->surname)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "codigo">Segundo apellido</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="second_surname"  value="{{old('second_surname', $user -> second_surname)}}" class="form-control">
		</div>
	</div>	
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "birthdate">Fecha de nacimiento</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="birthdate" required value="{{old('birthdate', $user->birthdate)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "address">Direccion</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="address" required value="{{old('address', $user->address)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "phone">Telefono</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="phone" required value="{{old('phone', $user->phone)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "email">Email</label>
			<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
			<input type="text" name="email" required value="{{old('email', $user->email)}}" class="form-control">
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for = "specialities">Especialidad</label>
			<div class="checkbox">
			@foreach($specialities as $id => $name)
			<label>
				<!-- para que se marquen los roles que hay usamos el siguiente pluck-->
				<input
					type="checkbox"
					required
					value="{{$id}}"
					{{$user->specialities->pluck('id')->contains($id) ? 'checked' : ''}}
					name="specialities[]"->{{$name}}
			</label>
			@endforeach
			<br>
		</div>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<label for="role">Roles</label>
		<div class="checkbox">
			@foreach($roles as $id => $name)
			<label>
				<!-- para que se marquen los roles que hay usamos el siguiente pluck-->
				<input
					type="checkbox"
					required
					value="{{$id}}"
					{{$user->roles->pluck('id')->contains($id) ? 'checked' : ''}}
					name="role[]"->{{$name}}
			</label>
			@endforeach
			<br>
		</div>
	</div>
	<!-- Para ocultar estos campos a la hora de actualizar, preguntamos si el usuario tiene un id. Si tiene un id significa que estamos editando y no lo muestra -->
	@unless ($user->id)
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for="password">Contraseña</label>
			<input class="form-control" type="password" name="password" required>
		</div>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<label for="password_confirmation">Confirma contraseña</label>
			<input class="form-control" type="password" name="password_confirmation" required>
		</div>
	</div>
	@endunless	
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<div class="form-group">
			<input class="btn btn-primary btn-lg btn-block" type="submit" value="{{$btnText}}">
		</div>
	</div>
</div>
<!-- /.row -->

resources/views/patients/index.blade.php
@extends('layouts.app')
@section('contenido')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper py-4">
    <!-- Main content -->
    <section class="content">
      	<div class="row">
        	<div class="col-12">
		        <div class="card">
		            <div class="card-header">
		            	<h3 class="card-title py-3">Pacientes</h3>
		              	<div class="row float-right py-3 px-3">
							<a href="{{route('paciente.create')}}"><i class="fas fa-plus" style="font-size: 20px"></i></a>						
						</div>
		            </div>
		            <!-- /.card-header -->
		            <div class="card-body">
		     			<table id="user" class="table table-bordered table-striped">
					        <thead>
				                <tr>
									<th>DNI</th>
									<th>Nombre</th>
									<th>Apellidos</th>
									<th>Telefono</th>
									<th>Email</th>
									<th>Profesional</th>
									<th>Opciones</th>
								</tr>
							</thead>
							<tbody>								
								@foreach ($patients as $patient)
								<tr>
									<td>{{$patient -> dni}}</td>	
									<td>{!!$patient->present()->link()!!}</td>
									<td>{{$patient -> surname.' ' .$patient -> second_surname}}</td>
									<td>{{$patient -> phone}}</td>	
									<td>{{$patient -> email}}</td>
									<td>{{$patient->present()->user()}}</td>										
									<td>										 
										<a href="{{route('paciente.edit', $patient->id)}}"><i class="far fa-edit px-2"></i></a>
										<a href="" data-target="#modal_delete{{$patient->id}}" data-toggle="modal"><i class="far fa-trash-alt px-2"></i></a>
									</td>
								</tr>
								@include('patients.modal')
								@endforeach
							</tbody>					
						</table>
					</div>		
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/patients/modal.blade.php
<div class="modal fade" id="modal_delete{{$patient->id}}">
  <div class="modal-dialog">
      <div class="modal-content">
        <form id="deleteuser" style="display:inline" method="POST" action="{{route('paciente.destroy',$patient->id)}}">
        @method('DELETE')
        @csrf

          <div class="modal-header">
              <h4 class="modal-title">Eliminar usuario {{$patient->name}}</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <p>Confirme si desea eliminar el usuario {{$patient->id}}</p>
          </div>
          <div class="modal-footer justify-content-between">
              <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
              <button class="btn btn-danger" type="submit" class="btn btn-primary" >Eliminar</button>
          </div>                     
        </form>
      </div>
      <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

resources/views/patients/show.blade.php
@extends('layouts.app')
@section('contenido')

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper py-3">
	  <!-- Main content -->
    <section class="content">      	
    	<div class="card">
            <div class="card-header">
            	<h3 class="card-title">{{$patient -> name.' ' .$patient -> surname.' ' .$patient -> second_surname}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">			
				<img class="py-2" width="100px" src="../img/fotoCV.jpg">
				<div class="row float-right py-3 px-3">
					<a href="{{route('paciente.edit', $patient->id)}}"><i class="far fa-edit px-4" style="font-size: 25px"></i></a>
					<a href="" data-target="#modal_delete{{$patient->id}}" data-toggle="modal"><i class="far fa-trash-alt px-3" style="font-size: 25px"></i></a>
					@include('patients.modal')
				</div>					
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "nombre"> DNI</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="dni" value="{{$patient -> dni}}" class="form-control"disabled style= "background-color:#FFFFFF ">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "name"> Nombre</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="name" value="{{$patient -> name}}" class="form-control"disabled style="background-color:#FFFFFF" >
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "surname">Apellido</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="surname" value="{{$patient -> surname}}" class="form-control"disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "second_surname">Segundo apellido</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="second_surname"  value="{{$patient -> second_surname}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "birthdate">Fecha de nacimiento</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="birthdate" value="{{$patient -> birthdate}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "address">Direccion</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="address" value="{{$patient -> address}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "phone">Telefono</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="phone" value="{{$patient -> phone}}" class="form-control" disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "email">Email</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="email" required value="{{$patient -> email}}" class="form-control"disabled style="background-color:#FFFFFF">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label for = "reason_visit">Email</label>
							<!-- name hace referencia al parametro llamado nombre que es recibido por categoria form Request -->
							<input type="text" name="reason_visit" required value="{{$patient -> reason_visit}}" class="form-control"disabled style="background-color:#FFFFFF">
						</div>
					</div>												
				</div>
				<!-- /.row -->
			</div>
			<!-- /.card-body -->
		</div>
		<!-- /.card -->
	</section>
</div>
@endsection